server:
  port: 8080
  servlet:
    context-path: /

spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  mail:
    protocol: smtp      # 邮箱协议
    host: smtp.163.com  # 网易邮箱 SMTP 服务器地址
    port: 25
    username: dang33431zhi@163.com  # 发件人邮箱地址
    password: IKRTIPGCVSEMDZZT      # 授权码
    default-encoding: utf-8
    properties:
      mail:
        debug: true # 开启 debug 模式会完整打印发送邮件的过程
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰映射